import { getAuthenticatedUserId } from "@/lib/auth"
import { NextRequest, NextResponse } from "next/server"
import { createIdea, findIdeas, findPinnedIdeas } from "@/db/ideas"
import { runEffect } from "@/lib/effect-runtime"
import type { Idea } from "@/db/schema"

const VALID_STATUSES: Idea["status"][] = ["inbox", "archived", "deleted"]

/** Ids generated by the offline outbox (`crypto.randomUUID()`). */
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function parseClientId(raw: unknown): string | null {
  return typeof raw === "string" && UUID_PATTERN.test(raw) ? raw : null
}

function parseIdeaStatus(raw: string | null): NonNullable<Idea["status"]> {
  const status = raw || ("inbox" as string)
  if (VALID_STATUSES.includes(status as NonNullable<Idea["status"]>)) {
    return status as NonNullable<Idea["status"]>
  }
  return "inbox"
}

// GET - Fetch all ideas (for web dashboard)
export async function GET(request: NextRequest) {
  try {
    const userId = await getAuthenticatedUserId(request)

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const status = parseIdeaStatus(searchParams.get("status"))
    const search = searchParams.get("search")
    const pinned = searchParams.get("pinned") === "true"
    const cursor = searchParams.get("cursor")
    const limit = Math.min(Number(searchParams.get("limit")) || 50, 100)

    let ideas
    let nextCursor: string | null = null

    if (pinned) {
      ideas = await runEffect(findPinnedIdeas({ userId }))
    } else {
      const results = await runEffect(
        findIdeas({
          userId,
          status,
          search,
          cursor,
          limit,
        }),
      )
      const hasMore = results.length > limit
      if (hasMore) results.pop()
      nextCursor = hasMore ? results[results.length - 1].created_at : null
      ideas = results
    }

    return NextResponse.json({ ideas, nextCursor })
  } catch (error) {
    console.error("Failed to fetch ideas:", error)
    return NextResponse.json({ error: "Failed to fetch ideas" }, { status: 500 })
  }
}

// POST - Create new idea
export async function POST(request: NextRequest) {
  try {
    const userId = await getAuthenticatedUserId(request)

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const source = request.headers.get("authorization")?.startsWith("Bearer ") ? "api" : "web"

    const body = await request.json()
    const { content, client_id } = body

    if (!content || typeof content !== "string" || content.trim().length === 0) {
      return NextResponse.json({ error: "Content is required" }, { status: 400 })
    }

    const values = {
      user_id: userId,
      content: content.trim(),
      source,
      status: "inbox" as const,
      pinned: 0,
      background_color: null,
    }

    // `client_id` keeps the id an offline capture already chose, so the local
    // row and the permanent row are the same idea instead of two ids with the
    // same content. A colliding id falls back to a server-generated one.
    const clientId = parseClientId(client_id)

    let idea
    try {
      idea = await runEffect(
        createIdea(clientId ? { ...values, id: clientId } : values),
      )
    } catch (error) {
      if (!clientId) throw error
      idea = await runEffect(createIdea(values))
    }

    return NextResponse.json({ idea }, { status: 201 })
  } catch (error) {
    console.error("Failed to create idea:", error)
    return NextResponse.json({ error: "Failed to create idea" }, { status: 500 })
  }
}
